---

dotfiles_repo: "https://github.com/jasesuperhero/dotfiles.git"
dotfiles_repo_accept_hostkey: no
dotfiles_repo_local_destination: "~/Documents/dotfiles"

dotfiles_home: "~"
dotfiles_files:
  - .bash_profile
  - .gitignore
  - .gitconfig
  - .inputrc
  - .vimrc
  - .aliases
  - .editorconfig
  - .exports
  - .functions