---
sudo: required
language: objective-c
osx_image: xcode7.3

before_install:
  - rm -rf /usr/local/Homebrew
  - rm -rf /usr/local/Caskroom
  - rm -rf /usr/local/bin/brew

install:
  - sudo easy_install pip
  - sudo pip install ansible
  - ansible --version
  - printf '[defaults]\nroles_path=../roles' >ansible.cfg
  - sudo mkdir -p /etc/ansible
  - sudo touch /etc/ansible/hosts
  - "echo -e '[local]\nlocalhost ansible_connection=local' | sudo tee -a /etc/ansible/hosts > /dev/null"

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml --syntax-check
  - ansible-playbook -v tests/test.yml -K