---

- hosts: localhost
  connection: local

  vars:
    rvm_rubies: ['ruby-2.5.1']
    rvm_bundler_install: True
    rvm_default_ruby_version: 'ruby-2.5.1'

    homebrew_installed_packages:
      - autoconf
      - antigen
      - bash-completion
      - doxygen
      - gettext
      - gifsicle
      - git
      - go
      - gpg
      - hub
      - httpie
      - iperf
      - libevent
      - sqlite
      - mcrypt
      - nmap
      - node
      - nvm
      - ssh-copy-id
      - readline
      - openssl
      - pv
      - wget
      - wrk
      - coreutils
      - moreutils
      - findutils
      - gnupg
      - neovim
      - grep
      - openssh
      - screen
      - defaultbrowser

    homebrew_cask_apps:
      - chromedriver
      - dropbox
      - firefox
      - google-chrome
      - handbrake
      - slack
      - telegram-desktop
      - visual-studio-code
      - fork
      - github
      - transmit
      - transmission
      - evernote
      - skitch
      - vlc
      - wireshark

    mas_installed_apps:
      - { id: 497799835, name: "Xcode (9.4.1)" }
      - { id: 425424353, name: "The Unarchiver (4.0.0)" }
      - { id: 441258766, name: "Magnet (2.2.2)" }
      - { id: 816239782, name: "joxi (3.0.42)" }
      - { id: 1176895641, name: "Spark (2.0.9)" }

    osx_script: "~/Documents/dotfiles/.osx --no-restart"

    default_browser_name: firefox
  roles:
    - ansible
    - homebrew
    - mas
    - zsh
    - rvm
    - dotfiles
    # - fonts
  
  # tasks:
  #   - include_tasks: tasks/osx.yml
  #     tags: ['osx']
