---
- hosts: localhost
  connection: local

  vars:
    homebrew_installed_packages:
      - autoconf
      - bash-completion
      - doxygen
      - gettext
      - gifsicle
      - git
      - go
      - gpg
      - hub
      - httpie
      - iperf
      - libevent
      - sqlite
      - mcrypt
      - nmap
      - node
      - nvm
      - ssh-copy-id
      - readline
      - openssl
      - pv
      - wget
      - wrk

    homebrew_cask_apps:
      - chromedriver
      - dropbox
      - firefox
      - google-chrome
      - handbrake
      - slack
      - telegram-desktop
      - visual-studio-code
      - fork
      - github
      - transmit
      - transmission
      - evernote
      - skitch
      - vlc
      - wireshark


    dotfiles_repo: "https://github.com/jasesuperhero/dotfiles.git"
    dotfiles_files:
      - .gitconfig
      - .hyper.js
      - .osx
      - .vimrc
      - .zshrc

  tasks:
    - include: tasks/ansible.yml

  roles:
    - geerlingguy.homebrew
    - geerlingguy.dotfiles
    - zsh
