---
- hosts: localhost
  connection: local

  vars:
    homebrew_installed_packages:
      - autoconf
      - bash-completion
      - git
      - carthage
      - gpg
      - boost
      - cmake
      - ssh-copy-id
      - openssl
      - wget
      - curl
      - argon/mas/mas
      - kylef/formulae/swiftenv

    homebrew_cask_apps:
      - firefox

  tasks:
    - include: tasks/ansible.yml

  roles:
    - geerlingguy.homebrew
