---

rvm_temp_download_path: '/tmp'

rvm_default_ruby_version: '{{ rvm_rubies | last if rvm_rubies and rvm_rubies is iterable else rvm_rubies }}'

rvm_rvm: '{{ rvm_install_path }}/bin/rvm'

rvm_symlink_binaries:
  - 'erb'
  - 'executable-hooks-uninstaller'
  - 'gem'
  - 'irb'
  - 'rake'
  - 'rdoc'
  - 'ri'
  - 'ruby'

rvm_symlink_bundler_binaries:
  - 'bundle'
  - 'bundler'

rvm_symlink_to: '/usr/local/bin'